---
blocklist:
  %{ for account in blocklist }- ${account}%{ endfor }

regions:
  - global
  %{ for region in regions ~}- ${region}
  %{ endfor ~}

bypass-alias-check-accounts:
  %{ for account in accounts ~}- ${account}
  %{ endfor ~}

resource-types:
  ## The following resource types included in the deletion process
  includes:
    %{ for resource, filters in included ~}- ${resource}
    %{ endfor ~}

  ## The following resources are excluded from the deletion process 
  excludes:
    %{ for resource in excluded ~}- ${resource}
    %{ endfor ~}

presets:
  %{ if length(global) > 0 }global:
    filters:
      __global__:
        %{ for filter in global }- property: "${filter.property}"
          type: "${filter.type}"
          value: "${filter.value}"
        %{ endfor }
  %{ endif }

  %{ for preset_name in keys(presets) }
  ${preset_name}:
    filters:
      %{ for resource, filters in presets[preset_name] ~}${resource}:
        %{ for filter in filters ~}- property: "${filter.property}"
          type: "${filter.type}"
          value: "${filter.value}"
          %{ if try(filter.invert, null) != null }}invert: ${filter.invert}%{ endif }
        %{ endfor }
      %{ endfor }
  %{ endfor }
## Iteratation of all the accounts, the resources and the filters 
## we should apply against those resources
accounts:
  %{ for account in accounts }${account}:
    presets:
      - %{ if length(global) > 0 }global%{ endif }
      %{ for name in keys(presets) ~}- ${name}
      %{ endfor }
  %{ endfor }
