---
name: Python Tests
on:
  push:
    branches:
      - main
    paths:
      - assets/docker/handler.py
      - assets/docker/test_handler.py
  pull_request:
    branches:
      - main
    paths:
      - assets/docker/handler.py
      - assets/docker/test_handler.py

permissions:
  contents: read

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip3 install pytest

      - name: Run Tests
        working-directory: assets/docker
        run: python3 -m pytest test_handler.py -v
