---
name: Python Tests
on:
  push:
    branches:
      - main
    paths:
      - assets/docker/handler.py
      - assets/docker/test_handler.py
  pull_request:
    branches:
      - main
    paths:
      - assets/docker/handler.py
      - assets/docker/test_handler.py

permissions:
  contents: read

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip3 install pytest

      - name: Run Tests
        working-directory: assets/docker
        run: python3 -m pytest test_handler.py -v
